[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

# REMOVE this unless you actually have Netlify Functions
# [functions]
#   directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
